type: MULTIPART
cases:
  fallback:
    model: "fluid_pipe_not_connected"
    variables:
      material: light_gray_shulker_box
  state[north=true]:
    model: "fluid_pipe_north"
    variables:
      material: light_gray_shulker_box
  state[east=true]:
    model: "fluid_pipe_east"
    variables:
      material: light_gray_shulker_box
  state[south=true]:
    model: "fluid_pipe_south"
    variables:
      material: light_gray_shulker_box
  state[west=true]:
    model: "fluid_pipe_west"
    variables:
      material: light_gray_shulker_box
  state[up=true]:
    model: "fluid_pipe_up"
    variables:
      material: light_gray_shulker_box
  state[down=true]:
    model: "fluid_pipe_down"
    variables:
      material: light_gray_shulker_box